name: Publish container images

on:
  push:
    branches:
      - main

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_INVITER_IMAGE_NAME: ${{ github.repository }}/inviter
  QUAY_REGISTRY: quay.io
  QUAY_INVITER_IMAGE_NAME: instructlab-ui/inviter

jobs:
  build_and_publish_ui_inviter_image:
    name: Push UI Inviter container image to GHCR and QUAY
    runs-on: ubuntu-latest
    environment: registry-creds
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the GHCR container image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Quay container image registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata (tags, labels) for UI Inviter image
        id: ghcr_inviter_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_INVITER_IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for UI image
        id: quay_inviter_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.QUAY_REGISTRY }}/${{ env.QUAY_INVITER_IMAGE_NAME }}

      - name: Build and push ui inviter image to ghcr.io
        id: push-inviter-ghcr
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.ghcr_inviter_meta.outputs.tags }}
          labels: ${{ steps.ghcr_inviter_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_INVITER_IMAGE_NAME}}
          subject-digest: ${{ steps.push-inviter-ghcr.outputs.digest }}
          push-to-registry: true

      - name: Build and push ui inviter image to quay.io
        id: push-inviter-quay
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.quay_inviter_meta.outputs.tags }}
          labels: ${{ steps.quay_inviter_meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
